# Form implementation generated from reading ui file 'screens\messagebox.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self):
        self.Form = QtWidgets.QWidget()
        self.Form.setObjectName("Form")
        self.Form.resize(505, 320)
        self.label_2 = QtWidgets.QLabel(parent=self.Form)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #6D6F11;\n"
"text-align: center;\n"
"font-family: Inter;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 140, 261, 21))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Please choose a rating "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
